<div id="column-left">
    <div class="box">
        <div class="box-heading"><span>Categorías</span></div>
        <div class="box-content">
            <ul class="box-category treemenu">
                <li>
                    <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=92"><span>Electrodomésticos y Aire Ac.</span></a>
                </li>
                <li>
                    <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=65"><span>Telefonos</span></a>
                    <ul>
                        <li>
                            <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=65_86"><span>Caterpillar</span></a>
                        </li>
                        <li>
                            <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=65_87"><span>Huawei</span></a>
                        </li>
                        <li>
                            <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=65_88"><span>Lg</span></a>
                        </li>
                        <li>
                            <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=65_89"><span>Motorola</span></a>
                        </li>
                        <li>
                            <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=65_70"><span>Samsung</span></a>
                        </li>
                        <li>
                            <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=65_71"><span>Sony</span></a>
                        </li>
                        <li>
                            <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=65_76"><span>Nokia</span></a>
                        </li>
                        <li>
                            <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=65_73"><span>Blackberry</span></a>
                        </li>
                        <li>
                            <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=65_72"><span>iPhone</span></a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=78"><span>GPS</span></a>
                </li>
                <li>
                    <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=84"><span>Cámaras Digitales</span></a>
                </li>
                <li>
                    <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=66"><span>Tablets</span></a>
                </li>
                <li>
                    <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=69"><span>Accesorios</span></a>
                    <ul>
                        <li>
                            <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=69_77"><span>Fundas</span></a>
                        </li>
                        <li>
                            <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=69_90"><span>Soportes Tv</span></a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=85"><span>Notebooks</span></a>
                    <ul>
                        <li>
                            <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=85_91"><span>Accessorios Notebook</span></a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=82"><span>Redes</span></a>
                    <ul>
                        <li>
                            <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=82_83"><span>Tp Link</span></a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=74"><span>Almacenamiento</span></a>
                    <ul>
                        <li>
                            <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=74_75"><span>Discos Portatiles</span></a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="http://www.gool.com.uy/index.php?route=product/category&amp;path=81"><span>Consolas</span></a>
                </li>
            </ul>
        </div>
    </div>
</div>