<div class="mpc-header clearfix">
    <!--<div class="mpc-logo">
        <h1><img src="Blaszok_files/logo.png" alt="Logo" height="26" width="165"></h1>
    </div>-->
    <div class="mpc-menu currency">
        Bienvenido,
        <div class="mpc-menu-item mpc-buy-now">
            <a id="mpc_buy_now" href="http://themeforest.net/item/blaszok-ultimate-multipurpose-responsive-theme/7163563?license=regular&amp;open_purchase_for_item_id=7163563&amp;purchasable=source" target="_blank">
                Acceder
            </a>
        </div>
        o
        <div class="mpc-menu-item mpc-buy-now">
            <a id="mpc_buy_now" href="http://themeforest.net/item/blaszok-ultimate-multipurpose-responsive-theme/7163563?license=regular&amp;open_purchase_for_item_id=7163563&amp;purchasable=source" target="_blank">
                Crear una cuenta
            </a>
        </div>
    </div>                    
    <div class="mpc-menu">
        <div class="mpc-menu-item mpc-menu-item-logo mpc-buy-now">
            <img src="<?php echo $this->basePath() ?>/img/logogool.png">
        </div>
        <div class="mpc-menu-item mpc-buy-now">
            <a id="mpc_favoritos" href="http://themeforest.net/item/blaszok-ultimate-multipurpose-responsive-theme/7163563?license=regular&amp;open_purchase_for_item_id=7163563&amp;purchasable=source" target="_blank">
                Favoritos (0)
            </a>
        </div>
        <div class="mpc-menu-item mpc-buy-now">
            <a id="mpc_su_cuenta" href="http://themeforest.net/item/blaszok-ultimate-multipurpose-responsive-theme/7163563?license=regular&amp;open_purchase_for_item_id=7163563&amp;purchasable=source" target="_blank">
                Su Cuenta
            </a>
        </div>
        <div class="mpc-menu-item mpc-buy-now">
            <a id="mpc_su_cesta" href="http://themeforest.net/item/blaszok-ultimate-multipurpose-responsive-theme/7163563?license=regular&amp;open_purchase_for_item_id=7163563&amp;purchasable=source" target="_blank">
                Su Cesta
            </a>
        </div>
        <div class="mpc-menu-item mpc-buy-now">
            <a id="mpc_pagar" href="http://themeforest.net/item/blaszok-ultimate-multipurpose-responsive-theme/7163563?license=regular&amp;open_purchase_for_item_id=7163563&amp;purchasable=source" target="_blank">
                Pagar
            </a>
        </div>
    </div>
    <div class="mpc-menu-mobile">
        <div id="mpc_shortcodes" class="mpc-mobile-submenu">
            <div class="mpc-mobile-submenu-col">
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/478-2/"><i class="fa fa-fw fa-bars"></i>Accordions</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/animations-viewport/"><i class="fa fa-fw fa-play-circle-o"></i>Animations<span class="mpc-label">HOT</span></a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/audio/"><i class="fa fa-fw fa-music"></i>Audio</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/blockquote/"><i class="fa fa-fw fa-quote-left"></i>Blockquote</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/brands-partners/"><i class="fa fa-fw fa-jpy"></i>Brands / Partners</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/buttons-2/"><i class="fa fa-fw fa-plus-square-o"></i>Buttons</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/call-out-box/"><i class="fa fa-fw fa-bullhorn"></i>Call Out Box</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/charts/"><i class="fa fa-fw fa-bar-chart-o"></i>Charts</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/code/"><i class="fa fa-fw fa-code"></i>Code</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/columns/"><i class="fa fa-fw fa-align-justify"></i>Columns</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/counters/"><i class="fa fa-fw fa-tachometer"></i>Counters</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/countdown/"><i class="fa fa-fw fa-tachometer"></i>Count Down<span class="mpc-label">NEW 3.1</span></a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/container/"><i class="fa fa-fw fa-square-o"></i>Container</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/content-slider/"><i class="fa fa-fw fa-youtube-play"></i>Content Slider</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/decor-headings/"><i class="fa fa-fw fa-font"></i>Decor Headings</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/dividers/"><i class="fa fa-fw fa-scissors"></i>Dividers</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/dropcaps/"><i class="fa fa-fw fa-text-height"></i>Dropcaps</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/faq/"><i class="fa fa-fw fa-question"></i>FAQ</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/feature-columns/"><i class="fa fa-fw fa-list-alt"></i>Feature Columns</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/flex-slider"><i class="fa fa-fw fa-youtube-play"></i>Flex Slider</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/highlight/"><i class="fa fa-fw fa-text-width"></i>Highlight</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/icon-lists/"><i class="fa fa-fw fa-list"></i>Icon Lists</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/icons/"><i class="fa fa-fw fa-asterisk"></i>Icons</a>
            </div>
            <div class="mpc-mobile-submenu-col">
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/image/"><i class="fa fa-fw fa-picture-o"></i>Image</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/image-carousel/"><i class="fa fa-fw fa-ellipsis-h"></i>Image Carousel</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/image-grid/"><i class="fa fa-fw fa-th-large"></i>Image Grid</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/layer-slider/"><i class="fa fa-fw fa-youtube-play"></i>Layer Slider 5<span class="mpc-label">NEW 1.1</span></a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/lightbox/"><i class="fa fa-fw fa-expand"></i>Lightbox</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/lookbook-slider/"><i class="fa fa-fw fa-youtube-play"></i>Lookbook Slider</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/map/"><i class="fa fa-fw fa-map-marker"></i>Map</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/message-boxes-alerts/"><i class="fa fa-fw fa-info"></i>Message Boxes / Alerts</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/nivo-slider/"><i class="fa fa-fw fa-youtube-play"></i>Nivo Slider</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/parallax/"><i class="fa fa-fw fa-desktop"></i>Parallax<span class="mpc-label">HOT</span></a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/recent-posts/"><i class="fa fa-fw fa-youtube-play"></i>Posts Slider</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/pricing-tables/"><i class="fa fa-fw fa-table"></i>Pricing Tables<span class="mpc-label">NEW 1.1</span></a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/product-category-slider/"><i class="fa fa-fw fa-youtube-play"></i>Product Category Slider</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/products-slider/"><i class="fa fa-fw fa-youtube-play"></i>Products Slider</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/recent-portfolio/"><i class="fa fa-fw fa-youtube-play"></i>Recent Portfolio</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/revolution-slider/"><i class="fa fa-fw fa-youtube-play"></i>Revolution Slider<span class="mpc-label">HOT</span></a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/share/"><i class="fa fa-fw fa-share-square-o"></i>Share</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/skills/"><i class="fa fa-fw fa-tasks"></i>Skills</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/tabs/"><i class="fa fa-fw fa-folder-o"></i>Tabs</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/tool-tip/"><i class="fa fa-fw fa-comment-o"></i>Tool Tip</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/tour/"><i class="fa fa-fw fa-list-ul"></i>Tour</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/video/"><i class="fa fa-fw fa-film"></i>Video</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/widgets/"><i class="fa fa-fw fa-cog"></i>Widgets</a>
            </div>
        </div>
        <div id="mpc_features" class="mpc-mobile-submenu">
            <div class="mpc-mobile-submenu-col">
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_meet_blaszok"><i class="fa-fw fa-power-off fa"></i>Meet Blaszok</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_ulitmate_bundle"><i class="fa-fw fa-gift fa"></i>Ultimate Bundle<span class="mpc-label">HOT</span></a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_design_styles"><i class="fa-fw fa-cogs fa"></i>Design Styles</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_woocommerce"><i class="fa-fw fa-shopping-cart fa"></i>Woocommerce</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_wishlist"><i class="fa-fw fa-list-ol fa"></i>Wishlist<span class="mpc-label">HOT</span></a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_mega_menu"><i class="fa-fw fa-magic fa"></i>Mega Menus<span class="mpc-label">HOT</span></a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_responsive"><i class="fa-fw fa-desktop fa"></i>Responsive &amp; Retina</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_wpml"><i class="fa-fw fa-font fa"></i>WPML Support</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_advanced_header"><i class="fa-fw fa-columns fa"></i>Advanced Header</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_search"><i class="fa-fw fa-search fa"></i>Smart Search<span class="mpc-label">HOT</span></a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_parallax"><i class="fa-fw fa-picture-o fa"></i>Parallax Sections</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_demo"><i class="fa-fw fa-magic fa"></i>One Click Install<span class="mpc-label">HOT</span></a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_essential"><i class="fa-fw fa-th-large fa"></i>Essential Grid<span class="mpc-label">NEW 2.1</span></a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_vc"><i class="fa-fw fa-wrench fa"></i>Visual Composer</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_revo"><i class="fa-fw fa-youtube-play fa"></i>Slider Revolution</a>
            </div>
            <div class="mpc-mobile-submenu-col">
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_pricing"><i class="fa-fw fa-table fa"></i>Pricing Tables<span class="mpc-label">NEW 1.1</span></a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_ls"><i class="fa-fw fa-youtube-play fa"></i>Layer Slider<span class="mpc-label">NEW 1.1</span></a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_seo"><i class="fa-fw fa-bullseye fa"></i>SEO Optimized</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_lookbook"><i class="fa-fw fa-folder-open-o fa"></i>Catalogues / Lookbooks</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_portfolio"><i class="fa-fw fa-camera-retro fa"></i>Portfolio</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_maintenance"><i class="fa-fw fa-table fa"></i>Maintenance<span class="mpc-label">NEW 3.1</span></a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_layouts"><i class="fa-fw fa-th-large fa"></i>Theme Layouts</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_backgrounds"><i class="fa-fw fa-folder-o fa"></i>Backgrounds</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_header_layouts"><i class="fa-fw fa-list-alt fa"></i>Header Layouts</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_skins"><i class="fa-fw fa-tint fa"></i>Skins &amp; Unlimited Colors</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_fonts"><i class="fa-fw fa-bold fa"></i>Fonts &amp; Typography</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_sidebars"><i class="fa-fw fa-th-list fa"></i>Sidebars &amp; Footers</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_blog"><i class="fa-fw fa-pencil fa"></i>Blog</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_support"><i class="fa-fw fa-star fa"></i>5 Star Support</a>
                <a target="_blank" href="http://blaszok.mpcthemes.net/default/features/#toc_demo"><i class="fa-fw fa-flask fa"></i>Demo Content</a>
            </div>
        </div>
        <div id="mpc_shortcodes" class="mpc-mobile-submenu">
            <a target="_blank" href="http://themeforest.net/item/blaszok-ultimate-multipurpose-responsive-theme/7163563?license=regular&amp;open_purchase_for_item_id=7163563&amp;purchasable=source">Buy Now!</a>
        </div>
    </div>
</div>