<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Gool - ' . $this->translate('Tecnología a tu alcance'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/footer.css')
                //->prependStylesheet($this->basePath() . '/css/common.css')
                ->prependStylesheet($this->basePath() . '/css/thirdeffect.css')
                ->prependStylesheet($this->basePath() . '/css/styles.css')
                ->prependStylesheet($this->basePath() . '/css/basic.css')
                ->prependStylesheet($this->basePath() . '/css/font-awesome.css')
                ->prependStylesheet($this->basePath() . '/css/main.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/scripts.js')
                //->prependFile($this->basePath() . '/js/main.js')
                ->prependFile($this->basePath() . '/js/jquery.infinitescroll.js')
                ->prependFile($this->basePath() . '/js/jquery.isotope.min.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/default.js')
                ->prependFile($this->basePath() . '/js/jquery-1.11.2.min.js')
                //->prependFile($this->basePath() . '/js/basic.js')
        ;
        ?>

    </head>
    <body>
<?php echo $this->content; ?>
<?php echo $this->inlineScript() ?>
    </body>
</html>
