<div id="mpc_grid" class="mpc-grid">
    <div id="mpc_filters" class="mpc-filters">
        <a class="mpc-filter mpc-active active" data-filter="*" href="#"><span>All</span></a>

        <a class="mpc-filter" data-filter=".cars" href="#"><span>Electrodomésticos y Aire Ac.</span></a>
        <a class="mpc-filter" data-filter=".phones" href="#"><span>GPS</span></a>
        <a class="mpc-filter" data-filter=".phones" href="#"><span>Cámaras Digitales</span></a>
        <a class="mpc-filter" data-filter=".phones" href="#"><span>Tablets</span></a>
        <a class="mpc-filter" data-filter=".phones" href="#"><span>Notebooks</span></a>
        <a class="mpc-filter" data-filter=".phones" href="#"><span>Redes</span></a>
        <a class="mpc-filter" data-filter=".phones" href="#"><span>Consolas</span></a>


<!--<a class="mpc-filter" data-filter=".fitness" href="#"><span>Fitness</span></a>-->

    </div>

</div>