<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/menu-puzzle.css'); ?>
<header role="banner" class="masthead">
    <nav role="navigation" class="menu">
        <ul class="menu-wrap rn_nav" id="nav">
            <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-126 mpc-filter" data-filter=".cars" id="menu-item-126"><a href="#">Electrodomésticos y Aire Ac.</a></li>
            <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-1036 mpc-filter" id="menu-item-1036">
                <a href="#">Telefonos</a>
                <ul class="sub-menu">
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1041" id="menu-item-1041 mpc-filter" data-filter=".phones">
                        <a href="#">First Child</a></li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-1040" id="menu-item-1040"><a href="https://puzzledemo.wordpress.com/a-parent-page/second-child/">Second Child</a>
                        <ul class="sub-menu">
                            <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1037" id="menu-item-1037"><a href="https://puzzledemo.wordpress.com/a-parent-page/second-child/a-grandchild-page/">A Grandchild Page</a></li>
                        </ul>
                    </li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1039" id="menu-item-1039"><a href="https://puzzledemo.wordpress.com/a-parent-page/third-child/">Third Child</a></li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1038" id="menu-item-1038"><a href="https://puzzledemo.wordpress.com/a-parent-page/fourth-child/">Fourth Child</a></li>
                </ul>
            </li>
            <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-126 mpc-filter" data-filter=".fitness" id="menu-item-126">
                <a href="#">GPS</a>
            </li>
            <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-126 mpc-filter" data-filter=".fitness" id="menu-item-126">
                <a href="#">Cámaras Digitales</a>
            </li>
            <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-126 mpc-filter" data-filter=".fitness" id="menu-item-126">
                <a href="#">Tablets</a>
            </li>
            <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-126 mpc-filter" data-filter=".fitness" id="menu-item-126">
                <a href="#">Notebooks</a>
            </li>
            <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-126 mpc-filter" data-filter=".fitness" id="menu-item-126">
                <a href="#">Redes</a>
            </li>
            <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-126 mpc-filter" data-filter=".fitness" id="menu-item-126">
                <a href="#">Consolas</a>
            </li>
            
        </ul><select class="rn_select" style="display: none;"><option value="">Menu</option><option value="https://puzzledemo.wordpress.com/html-elements/">HTML Elements</option><option value="https://puzzledemo.wordpress.com/a-parent-page/first-child/">- First Child</option><option value="https://puzzledemo.wordpress.com/a-parent-page/second-child/">- Second Child</option><option value="https://puzzledemo.wordpress.com/a-parent-page/second-child/a-grandchild-page/">-- A Grandchild Page</option><option value="https://puzzledemo.wordpress.com/a-parent-page/third-child/">- Third Child</option><option value="https://puzzledemo.wordpress.com/a-parent-page/fourth-child/">- Fourth Child</option><option value="#">Writing</option><option value="https://puzzledemo.wordpress.com/category/artwork/">Artwork</option><option value="https://puzzledemo.wordpress.com/category/books/">Books</option><option value="https://puzzledemo.wordpress.com/category/wordpress/">WordPress</option></select>		</nav>
</header>