<!DOCTYPE html>
<html class="no-js">
    <body class="mpc-loaded">
        <div class="mpc-load">
            <div class="mpc-ball-one"></div>
            <div class="mpc-ball-two"></div>
        </div>
        <div class="mpc-content">
            <?php echo $this->partial('layout/header'); ?>
            <div class="mpc-preview">

                <div class="background-fixed">
                    <div class="texto">
                        <p>Tel: 2 709 03 24</p>
                        <p>Sucursal Pocitos: 26 de Marzo 3454Bis (<strong>ver mapa</strong>)</p>
                        <p>Sucursal Centro: Plaza Independencia 705 (<strong>ver mapa</strong>)</p>
                    </div>
                    <div class="buscar">
                        <input type="text" placeholder="Buscar..">
                        <input type="image" src="<?php echo $this->basePath() ?>/img/icon-search.png">
                    </div>
                    <div class="items">
                        <a><span id="cart-total">0 articulo(s) - 0 USD</span></a>
                    </div>
                </div>
            </div>

            <div class="container outer-container">
                <?php echo $this->partial('layout/menu-productos_nuevo'); ?>
                <div id="wrap">
                    <div class="view third-effect box box-500-500 third-effect-500-500 fitness" data-type="fitness"  data-value=12>
                        <img src="<?php echo $this->basePath() ?>/img/500-500.jpg">
                        <div class="mask mask-500-500">
                            <div class="detalle-producto-puzzle">
                                <h3>Titulo del producto</h3><p>Descripcion del producto</p><div class='btns-acciones-puzzle'>
                                    <a href="#" class="btn-comprar-puzzle">Comprar!</a><a href="#" class="btn-add-wish-puzzle">&nbsp;</a></div>
                            </div>
                        </div>
                        <div class="content">
                            <a href="#" class="info" title="Full Image">Full Image</a>  
                        </div>  
                    </div>
                    <div class="view third-effect third-effect-500-250 box box-500-250 fitness" data-type="fitness"  data-value=12>
                        <img src="<?php echo $this->basePath() ?>/img/500-250.jpg">
                        <div class="mask mask-500-250">
                            <div class="detalle-producto-puzzle">
                                <h3>Titulo del producto</h3><p>Descripcion del producto</p><div class='btns-acciones-puzzle'>
                                    <a href="#" class="btn-comprar-puzzle">Comprar!</a><a href="#" class="btn-add-wish-puzzle">&nbsp;</a></div>
                            </div>
                        </div>
                        <div class="content">  
                            <a href="#" class="info" title="Full Image">Full Image</a>  
                        </div>  
                    </div>
                    <div class="view third-effect third-effect-250-250 box box-250-250 fitness" data-type="fitness"  data-value=12>
                        <img src="<?php echo $this->basePath() ?>/img/250-250.jpg">
                        <div class="mask mask-250-250">
                            <div class="detalle-producto-puzzle">
                                <h3>Titulo del producto</h3><p>Descripcion del producto</p><div class='btns-acciones-puzzle'>
                                    <a href="#" class="btn-comprar-puzzle">Comprar!</a><a href="#" class="btn-add-wish-puzzle">&nbsp;</a></div>
                            </div>
                        </div>
                        <div class="content">  
                            <a href="#" class="info" title="Full Image">Full Image</a>  
                        </div>  
                    </div>
                    <div class="view third-effect third-effect-250-250 box box-250-250 fitness" data-type="fitness"  data-value=12>
                        <img src="<?php echo $this->basePath() ?>/img/250-250.jpg">
                        <div class="mask mask-250-250">
                            <div class="detalle-producto-puzzle">
                                <h3>Titulo del producto</h3><p>Descripcion del producto</p><div class='btns-acciones-puzzle'>
                                    <a href="#" class="btn-comprar-puzzle">Comprar!</a><a href="#" class="btn-add-wish-puzzle">&nbsp;</a></div>
                            </div>
                        </div>
                        <div class="content">  
                            <a href="#" class="info" title="Full Image">Full Image</a>  
                        </div>  
                    </div>
                    <div class="view third-effect third-effect-500-250 box box-500-250 fitness" data-type="fitness"  data-value=12>
                        <img src="<?php echo $this->basePath() ?>/img/500-250.jpg">
                        <div class="mask mask-500-250">
                            <div class="detalle-producto-puzzle">
                                <h3>Titulo del producto</h3><p>Descripcion del producto</p><div class='btns-acciones-puzzle'>
                                    <a href="#" class="btn-comprar-puzzle">Comprar!</a><a href="#" class="btn-add-wish-puzzle">&nbsp;</a></div>
                            </div>
                        </div>
                        <div class="content">  
                            <a href="#" class="info" title="Full Image">Full Image</a>  
                        </div>  
                    </div>

                    <div class="view third-effect third-effect-500-500 box box-500-500 third-effect-500-500 cars" data-type="cars" data-value=5>
                        <img src="<?php echo $this->basePath() ?>/img/500-500.jpg">
                        <div class="mask mask-500-500">
                            <div class="detalle-producto-puzzle">
                                <h3>Titulo del producto</h3><p>Descripcion del producto</p><div class='btns-acciones-puzzle'>
                                    <a href="#" class="btn-comprar-puzzle">Comprar!</a><a href="#" class="btn-add-wish-puzzle">&nbsp;</a></div>
                            </div>
                        </div>
                        <div class="content">  
                            <a href="#" class="info" title="Full Image">Full Image</a>  
                        </div>  
                    </div>        
                    <div class="view third-effect third-effect-250-250 box box-250-250 cars" data-type="cars" data-value=5>
                        <img src="<?php echo $this->basePath() ?>/img/250-250.jpg">
                        <div class="mask mask-250-250">
                            <div class="detalle-producto-puzzle">
                                <h3>Titulo del producto</h3><p>Descripcion del producto</p><div class='btns-acciones-puzzle'>
                                    <a href="#" class="btn-comprar-puzzle">Comprar!</a><a href="#" class="btn-add-wish-puzzle">&nbsp;</a></div>
                            </div>
                        </div>
                        <div class="content">  
                            <a href="#" class="info" title="Full Image">Full Image</a>  
                        </div>  
                    </div>        
                    <div class="view third-effect third-effect-500-250 box box-500-250 cars" data-type="cars" data-value=5>
                        <img src="<?php echo $this->basePath() ?>/img/500-250.jpg">
                        <div class="mask mask-500-250">
                            <div class="detalle-producto-puzzle">
                                <h3>Titulo del producto</h3><p>Descripcion del producto</p><div class='btns-acciones-puzzle'>
                                    <a href="#" class="btn-comprar-puzzle">Comprar!</a><a href="#" class="btn-add-wish-puzzle">&nbsp;</a></div>
                            </div>
                        </div>
                        <div class="content">  
                            <a href="#" class="info" title="Full Image">Full Image</a>  
                        </div>  
                    </div>
                    <div class="view third-effect third-effect-500-250 box box-500-250 cars" data-type="cars" data-value=5>
                        <img src="<?php echo $this->basePath() ?>/img/500-250.jpg">
                        <div class="mask mask-500-250">
                            <div class="detalle-producto-puzzle">
                                <h3>Titulo del producto</h3><p>Descripcion del producto</p><div class='btns-acciones-puzzle'>
                                    <a href="#" class="btn-comprar-puzzle">Comprar!</a><a href="#" class="btn-add-wish-puzzle">&nbsp;</a></div>
                            </div>
                        </div>
                        <div class="content">  
                            <a href="#" class="info" title="Full Image">Full Image</a>  
                        </div>  
                    </div>        
                    <div class="view third-effect third-effect-250-250 box box-250-250 cars" data-type="cars" data-value=5>
                        <img src="<?php echo $this->basePath() ?>/img/250-250.jpg">
                        <div class="mask mask-250-250">
                            <div class="detalle-producto-puzzle">
                                <h3>Titulo del producto</h3><p>Descripcion del producto</p><div class='btns-acciones-puzzle'>
                                    <a href="#" class="btn-comprar-puzzle">Comprar!</a><a href="#" class="btn-add-wish-puzzle">&nbsp;</a></div>
                            </div>
                        </div>
                        <div class="content">  
                            <a href="#" class="info" title="Full Image">Full Image</a>  
                        </div>  
                    </div>        

                    <div class="view third-effect third-effect-500-500 box box-500-500 third-effect-500-500 phones" data-type="phones"  data-value=12>
                        <img src="<?php echo $this->basePath() ?>/img/500-500.jpg">
                        <div class="mask mask-500-500">
                            <div class="detalle-producto-puzzle">
                                <h3>Titulo del producto</h3><p>Descripcion del producto</p><div class='btns-acciones-puzzle'>
                                    <a href="#" class="btn-comprar-puzzle">Comprar!</a><a href="#" class="btn-add-wish-puzzle">&nbsp;</a></div>
                            </div>
                        </div>
                        <div class="content">  
                            <a href="#" class="info" title="Full Image">Full Image</a>  
                        </div>  
                    </div>
                    <div class="view third-effect third-effect-500-250 box box-500-250 phones" data-type="phones"  data-value=12>
                        <img src="<?php echo $this->basePath() ?>/img/500-250.jpg">
                        <div class="mask mask-500-250">
                            <div class="detalle-producto-puzzle">
                                <h3>Titulo del producto</h3><p>Descripcion del producto</p><div class='btns-acciones-puzzle'>
                                    <a href="#" class="btn-comprar-puzzle">Comprar!</a><a href="#" class="btn-add-wish-puzzle">&nbsp;</a></div>
                            </div>
                        </div>
                        <div class="content">  
                            <a href="#" class="info" title="Full Image">Full Image</a>  
                        </div>  
                    </div>
                    <div class="view third-effect third-effect-250-250 box box-250-250 phones" data-type="phones"  data-value=12>
                        <img src="<?php echo $this->basePath() ?>/img/250-250.jpg">
                        <div class="mask mask-250-250">
                            <div class="detalle-producto-puzzle">
                                <h3>Titulo del producto</h3><p>Descripcion del producto</p><div class='btns-acciones-puzzle'>
                                    <a href="#" class="btn-comprar-puzzle">Comprar!</a><a href="#" class="btn-add-wish-puzzle">&nbsp;</a></div>
                            </div>
                        </div>
                        <div class="content">  
                            <a href="#" class="info" title="Full Image">Full Image</a>  
                        </div>  
                    </div>
                    <div class="view third-effect third-effect-250-250 box box-250-250 phones" data-type="phones"  data-value=12>
                        <img src="<?php echo $this->basePath() ?>/img/250-250.jpg">
                        <div class="mask mask-250-250">
                            <div class="detalle-producto-puzzle">
                                <h3>Titulo del producto</h3><p>Descripcion del producto</p><div class='btns-acciones-puzzle'>
                                    <a href="#" class="btn-comprar-puzzle">Comprar!</a><a href="#" class="btn-add-wish-puzzle">&nbsp;</a></div>
                            </div>
                        </div>
                        <div class="content">  
                            <a href="#" class="info" title="Full Image">Full Image</a>  
                        </div>  
                    </div>
                    <div class="view third-effect third-effect-500-250 box box-500-250 phones" data-type="phones"  data-value=12>
                        <img src="<?php echo $this->basePath() ?>/img/500-250.jpg">
                        <div class="mask mask-500-250">
                            <div class="detalle-producto-puzzle">
                                <h3>Titulo del producto</h3><p>Descripcion del producto</p><div class='btns-acciones-puzzle'>
                                    <a href="#" class="btn-comprar-puzzle">Comprar!</a><a href="#" class="btn-add-wish-puzzle">&nbsp;</a></div>
                            </div>
                        </div>
                        <div class="content">  
                            <a href="#" class="info" title="Full Image">Full Image</a>  
                        </div>  
                    </div>
                </div>
                <!--<nav id="page_nav" style="display: none;">
                    <a href="application/index/masonry<?php //echo $this->url("application", array("controller" => "index", "action" => "masonry"))  ?>"></a>
                </nav>-->

            </div> <!-- /container -->
            <?php echo $this->partial('layout/footer'); ?>
        </div>
    </body>
</html>
