<div class="view third-effect box box-500-500 third-effect-500-500 fitness" data-type="fitness"  data-value=12>
    <img src="<?php echo $this->basePath() ?>/img/500-500.jpg">
    <div class="mask mask-500-500">
        <div class="detalle-producto-puzzle">
            <p>Descripcion del producto</p>
            <p><a href="#" class="">Comprar!</a></p>
        </div>
    </div>
    <div class="content">
        <a href="#" class="info" title="Full Image">Full Image</a>  
    </div>  
</div>
<div class="view third-effect third-effect-500-250 box box-500-250 fitness" data-type="fitness"  data-value=12>
    <img src="<?php echo $this->basePath() ?>/img/500-250.jpg">
    <div class="mask mask-500-250">
        <div class="detalle-producto-puzzle">
            <p>Descripcion del producto</p>
            <p><a href="#" class="">Comprar!</a></p>
        </div>
    </div>
    <div class="content">  
        <a href="#" class="info" title="Full Image">Full Image</a>  
    </div>  
</div>
<div class="view third-effect third-effect-250-250 box box-250-250 fitness" data-type="fitness"  data-value=12>
    <img src="<?php echo $this->basePath() ?>/img/250-250.jpg">
    <div class="mask mask-250-250">
        <div class="detalle-producto-puzzle">
            <p>Descripcion del producto</p>
            <p><a href="#" class="">Comprar!</a></p>
        </div>
    </div>
    <div class="content">  
        <a href="#" class="info" title="Full Image">Full Image</a>  
    </div>  
</div>
<div class="view third-effect third-effect-250-250 box box-250-250 fitness" data-type="fitness"  data-value=12>
    <img src="<?php echo $this->basePath() ?>/img/250-250.jpg">
    <div class="mask mask-250-250">
        <div class="detalle-producto-puzzle">
            <p>Descripcion del producto</p>
            <p><a href="#" class="">Comprar!</a></p>
        </div>
    </div>
    <div class="content">  
        <a href="#" class="info" title="Full Image">Full Image</a>  
    </div>  
</div>
<div class="view third-effect third-effect-500-250 box box-500-250 fitness" data-type="fitness"  data-value=12>
    <img src="<?php echo $this->basePath() ?>/img/500-250.jpg">
    <div class="mask mask-500-250">
        <div class="detalle-producto-puzzle">
            <p>Descripcion del producto</p>
            <p><a href="#" class="">Comprar!</a></p>
        </div>
    </div>
    <div class="content">  
        <a href="#" class="info" title="Full Image">Full Image</a>  
    </div>  
</div>

<div class="view third-effect third-effect-500-500 box box-500-500 third-effect-500-500 cars" data-type="cars" data-value=5>
    <img src="<?php echo $this->basePath() ?>/img/500-500.jpg">
    <div class="mask mask-500-500">
        <div class="detalle-producto-puzzle">
            <p>Descripcion del producto</p>
            <p><a href="#" class="">Comprar!</a></p>
        </div>
    </div>
    <div class="content">  
        <a href="#" class="info" title="Full Image">Full Image</a>  
    </div>  
</div>        
<div class="view third-effect third-effect-250-250 box box-250-250 cars" data-type="cars" data-value=5>
    <img src="<?php echo $this->basePath() ?>/img/250-250.jpg">
    <div class="mask mask-250-250">
        <div class="detalle-producto-puzzle">
            <p>Descripcion del producto</p>
            <p><a href="#" class="">Comprar!</a></p>
        </div>
    </div>
    <div class="content">  
        <a href="#" class="info" title="Full Image">Full Image</a>  
    </div>  
</div>        
<div class="view third-effect third-effect-500-250 box box-500-250 cars" data-type="cars" data-value=5>
    <img src="<?php echo $this->basePath() ?>/img/500-250.jpg">
    <div class="mask mask-500-250">
        <div class="detalle-producto-puzzle">
            <p>Descripcion del producto</p>
            <p><a href="#" class="">Comprar!</a></p>
        </div>
    </div>
    <div class="content">  
        <a href="#" class="info" title="Full Image">Full Image</a>  
    </div>  
</div>
<div class="view third-effect third-effect-500-250 box box-500-250 cars" data-type="cars" data-value=5>
    <img src="<?php echo $this->basePath() ?>/img/500-250.jpg">
    <div class="mask mask-500-250">
        <div class="detalle-producto-puzzle">
            <p>Descripcion del producto</p>
            <p><a href="#" class="">Comprar!</a></p>
        </div>
    </div>
    <div class="content">  
        <a href="#" class="info" title="Full Image">Full Image</a>  
    </div>  
</div>        
<div class="view third-effect third-effect-250-250 box box-250-250 cars" data-type="cars" data-value=5>
    <img src="<?php echo $this->basePath() ?>/img/250-250.jpg">
    <div class="mask mask-250-250">
        <div class="detalle-producto-puzzle">
            <p>Descripcion del producto</p>
            <p><a href="#" class="">Comprar!</a></p>
        </div>
    </div>
    <div class="content">  
        <a href="#" class="info" title="Full Image">Full Image</a>  
    </div>  
</div>        

<div class="view third-effect third-effect-500-500 box box-500-500 third-effect-500-500 phones" data-type="phones"  data-value=12>
    <img src="<?php echo $this->basePath() ?>/img/500-500.jpg">
    <div class="mask mask-500-500">
        <div class="detalle-producto-puzzle">
            <p>Descripcion del producto</p>
            <p><a href="#" class="">Comprar!</a></p>
        </div>
    </div>
    <div class="content">  
        <a href="#" class="info" title="Full Image">Full Image</a>  
    </div>  
</div>
<div class="view third-effect third-effect-500-250 box box-500-250 phones" data-type="phones"  data-value=12>
    <img src="<?php echo $this->basePath() ?>/img/500-250.jpg">
    <div class="mask mask-500-250">
        <div class="detalle-producto-puzzle">
            <p>Descripcion del producto</p>
            <p><a href="#" class="">Comprar!</a></p>
        </div>
    </div>
    <div class="content">  
        <a href="#" class="info" title="Full Image">Full Image</a>  
    </div>  
</div>
<div class="view third-effect third-effect-250-250 box box-250-250 phones" data-type="phones"  data-value=12>
    <img src="<?php echo $this->basePath() ?>/img/250-250.jpg">
    <div class="mask mask-250-250">
        <div class="detalle-producto-puzzle">
            <p>Descripcion del producto</p>
            <p><a href="#" class="">Comprar!</a></p>
        </div>
    </div>
    <div class="content">  
        <a href="#" class="info" title="Full Image">Full Image</a>  
    </div>  
</div>
<div class="view third-effect third-effect-250-250 box box-250-250 phones" data-type="phones"  data-value=12>
    <img src="<?php echo $this->basePath() ?>/img/250-250.jpg">
    <div class="mask mask-250-250">
        <div class="detalle-producto-puzzle">
            <p>Descripcion del producto</p>
            <p><a href="#" class="">Comprar!</a></p>
        </div>
    </div>
    <div class="content">  
        <a href="#" class="info" title="Full Image">Full Image</a>  
    </div>  
</div>
<div class="view third-effect third-effect-500-250 box box-500-250 phones" data-type="phones"  data-value=12>
    <img src="<?php echo $this->basePath() ?>/img/500-250.jpg">
    <div class="mask mask-500-250">
        <div class="detalle-producto-puzzle">
            <p>Descripcion del producto</p>
            <p><a href="#" class="">Comprar!</a></p>
        </div>
    </div>
    <div class="content">  
        <a href="#" class="info" title="Full Image">Full Image</a>  
    </div>  
</div>